<h1>Login </h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare();
echo $this->form()->openTag($form);

?>
<table class="table">
<tr>
    <th>Email</th>
	<th>Password</th>
    <th>&nbsp;</th>
</tr>
<tr>
    <td><?php echo $this->formRow($form->get('email')); ?></td>
	<td><?php echo $this->formRow($form->get('password')); ?></td>
	<td><?php echo $this->formRow($form->get('rememberme')); ?></td>
</tr>

</table>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->name);
?>		
 | <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a> 
<?php
    } else {
        echo 'Not logged in';
    }
?>
<p>
	<a href="<?php echo $this->url('user', array('controller' => 'user', 'action' => 'add'));?>"><?php echo $this->translate('Register'); ?></a>
	
</p>