 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Registration';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('user', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo '<br />';
 echo $this->formHidden($form->get('id'));
 ?>
 <table class="table">
<tr>
    <th>Name</th>
    <th>Email</th>
	<th>Password</th>
    <th>&nbsp;</th>
</tr>
<tr>
    <td><?php echo $this->formRow($form->get('name')); ?></td>
	<td><?php echo $this->formRow($form->get('email')); ?></td>
	<td><?php echo $this->formRow($form->get('password')); ?></td>
	
</tr>

</table>
<?php

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
 