<?php

$title = 'Edit User';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<table class="table">
<tr>
    <th>Name</th>
    <th>Email</th>
	<th>Gendder</th>
	<th>Age</th>
	<th>Occupancy</th>
	<th>Password</th>
    <th>&nbsp;</th>
</tr>
<tr>
    <td><?php echo $this->formRow($form->get('name')); ?></td>
	<td><?php echo $this->formRow($form->get('email')); ?></td>
	<td><?php echo $this->formRadio($form->get('gender')); ?></td>
	<td><?php echo $this->formRow($form->get('age')); ?></td>
	<td><?php echo $this->formRow($form->get('occupancy')); ?></td>
	<td><?php echo $this->formRow($form->get('password')); ?></td>
	
</tr>

</table>
<?php

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();