 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add Restaurant';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
<div style="height:800px">
	<?php
	$form->setAttribute('action', $this->url('restaurant', array('action' => 'add')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id')); 
	echo $this->formHidden($form->get('lat'));
	echo $this->formHidden($form->get('lng'));
	?>
	<table class="table">
	<tr>
		<th>Name</th>
		<th>Address</th>
		<th>Contact</th>
		<th>Website</th>
		<th>&nbsp;</th>
	</tr>

	<tr>
		
		<td><?php echo $this->formRow($form->get('name')); ?></td>
		<td><?php echo $this->formRow($form->get('address')); ?></td>
		<td><?php echo $this->formRow($form->get('contact')); ?></td>
		<td><?php echo $this->formRow($form->get('site')); ?></td>
		
	</tr>

	</table>

	<?php
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	?>
 
	<div id="map"></div>

 
	<?php $this->inlineScript()->appendFile('/js/my.googlemap.js'); ?>
	<?php echo $this->inlineScript()->prependFile('https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete') ?>

</div>

