<?php

$title = 'Restaurants';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('restaurant', array('action'=>'add'));?>">Create Restaurant</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Address</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($restaurants as $restaurant) : ?>
<tr>
    <td><?php echo $this->escapeHtml($restaurant->name);?></td>
    <td><?php echo $this->escapeHtml($restaurant->address);?></td>
	<td>
        <a href="<?php echo $this->url('restaurant',
            array('action'=>'view', 'id' => $restaurant->id));?>">View</a>
    </td>
    <td>
        <a href="<?php echo $this->url('restaurant',
            array('action'=>'edit', 'id' => $restaurant->id));?>">Update</a>
    </td>
	<td>
        <a href="<?php echo $this->url('userFavoriteRestaurant',
            array('action'=>'favorite', 'id' => $restaurant->id));?>">Add to Favorites</a>
    </td>
	<td>
        <a href="<?php echo $this->url('restaurant',
            array('action'=>'restaurantImages', 'id' => $restaurant->id));?>">Upload Photo</a>
    </td>
</tr>
<?php endforeach; ?>
</table>